version: '3'

services:
  server:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '1000:3001'

  database:
    build: database/
    environment: 
      MYSQL_PASSWORD: 'nick'
      MYSQL_DATABASE: 'photos'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'nick'
    ports:
     - '3306:3306'

  seed:
    build: server/
    depends_on:
      - 'server'
    ports:
      - '3002:3002'